import json
import asyncio
import math
from datetime import datetime
from playwright.async_api import async_playwright

COOKIES_JSON = "cookies.json"
COOKIES_TXT  = "cookies.txt"


# ─────────────────────────────────────────────
# Helpers: chuyển đổi giữa JSON ↔ Netscape TXT
# ─────────────────────────────────────────────

def _bool(v: bool) -> str:
    return "TRUE" if v else "FALSE"


def cookies_to_netscape(cookies: list[dict]) -> str:
    """Chuyển list cookie (Playwright format) → chuỗi Netscape cookie file."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by yt-dlp.  Do not edit.",
        "",
    ]
    for c in cookies:
        domain: str = c.get("domain", "")
        # Netscape: include_subdomains = True nếu domain bắt đầu bằng dấu chấm
        include_sub = _bool(domain.startswith("."))
        path        = c.get("path", "/")
        secure      = _bool(c.get("secure", False))
        # expires: Playwright dùng float giây; -1 hoặc 0 → session cookie → lưu 0
        expires_raw = c.get("expires", 0)
        if expires_raw is None or expires_raw < 0 or math.isnan(float(expires_raw)):
            expires_int = 0
        else:
            expires_int = int(expires_raw)
        name  = c.get("name", "")
        value = c.get("value", "")
        lines.append(
            f"{domain}\t{include_sub}\t{path}\t{secure}\t{expires_int}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


def netscape_to_cookies(txt: str) -> list[dict]:
    """Chuyển chuỗi Netscape cookie file → list cookie (Playwright format)."""
    cookies = []
    for line in txt.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        domain, include_sub, path, secure, expires_str, name, value = parts[:7]
        try:
            expires = int(expires_str)
        except ValueError:
            expires = 0
        cookies.append({
            "name":     name,
            "value":    value,
            "domain":   domain,
            "path":     path,
            "expires":  expires if expires > 0 else -1,
            "httpOnly": False,          # TXT không lưu httpOnly → mặc định False
            "secure":   secure == "TRUE",
            "sameSite": "Lax",
        })
    return cookies


# ─────────────────────────────────────────────
# Load / Save
# ─────────────────────────────────────────────

def load_cookies() -> list[dict]:
    """Ưu tiên load cookies.json, fallback sang cookies.txt."""
    # Thử JSON trước
    try:
        with open(COOKIES_JSON, "r", encoding="utf-8") as f:
            cookies = json.load(f)
        print(f"🍪 Loaded {len(cookies)} cookies từ {COOKIES_JSON}")
        return cookies
    except FileNotFoundError:
        pass
    except Exception as e:
        print(f"⚠️  Đọc {COOKIES_JSON} lỗi: {e}")

    # Fallback: TXT
    try:
        with open(COOKIES_TXT, "r", encoding="utf-8") as f:
            cookies = netscape_to_cookies(f.read())
        print(f"🍪 Loaded {len(cookies)} cookies từ {COOKIES_TXT}")
        return cookies
    except FileNotFoundError:
        pass
    except Exception as e:
        print(f"⚠️  Đọc {COOKIES_TXT} lỗi: {e}")

    print("⚠️  Chưa có cookies, đăng nhập mới.")
    return []


def save_cookies(cookies: list[dict]) -> None:
    """Lưu cookies ra cả JSON lẫn Netscape TXT."""
    # JSON
    with open(COOKIES_JSON, "w", encoding="utf-8") as f:
        json.dump(cookies, f, ensure_ascii=False, indent=2)
    print(f"✅ Đã lưu {len(cookies)} cookies → {COOKIES_JSON}")

    # Netscape TXT
    with open(COOKIES_TXT, "w", encoding="utf-8") as f:
        f.write(cookies_to_netscape(cookies))
    print(f"✅ Đã lưu {len(cookies)} cookies → {COOKIES_TXT}")

    # Thông tin nhanh về session TikTok
    session = next((c for c in cookies if c.get("name") == "sessionid"
                    and "tiktok.com" in c.get("domain", "")), None)
    if session:
        exp = session.get("expires", 0)
        if exp and exp > 0:
            exp_str = datetime.utcfromtimestamp(exp).strftime("%Y-%m-%d %H:%M UTC")
            print(f"🔑 TikTok sessionid hết hạn: {exp_str}")
    else:
        print("⚠️  Không tìm thấy TikTok sessionid trong cookies!")


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            args=[
                "--disable-blink-features=AutomationControlled",
                "--disable-popup-blocking",
                "--no-sandbox",
            ],
        )
        context = await browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 800},
        )

        # Tự đưa popup lên foreground
        context.on("page", lambda page: asyncio.ensure_future(page.bring_to_front()))

        # Load cookies cũ
        existing = load_cookies()
        if existing:
            await context.add_cookies(existing)

        page = await context.new_page()
        await page.goto("https://www.tiktok.com/login", wait_until="domcontentloaded")

        print("\n" + "=" * 50)
        input("⏳ Đăng nhập TikTok xong thì nhấn Enter...")
        print("=" * 50 + "\n")

        cookies = await context.cookies()
        save_cookies(cookies)

        await browser.close()


if __name__ == "__main__":
    asyncio.run(main())